name: Testing on pull requests
on:
  pull_request:
    types: [opened, synchronized, edited]
  jobs:
    test:
      runs-on: ubuntu-20.04
      steps:
        - uses: action/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 15
        - name: Install dependencies
          run: npm --frozen-lockfile
        -name: Test the code
          run: npm run test